from pathlib import Path

# MAIN CONSTANTS
VERSION_KEY = "version"
EXPECTED_VERSION = 2

# SCHEMA KEYS
SCHEMA_TYPE_KEY = "type"
SCHEMA_HELP_KEY = "help"
SCHEMA_DEFAULT_KEY = "default"
SCHEMA_MUTATOR_KEY = "mutator"
SCHEMA_VERIFIER_KEY = "verifier"

# field is set auto.
MAIN_DIR_FIELD = ("main_dir",)

# Keys for chain section
CHAIN_SECTION_KEY = "chain"
CHAIN_NAME_FIELD = (CHAIN_SECTION_KEY, "name")  # Can't be set with config.json, field is set auto.
CHAIN_START_SLOT_FIELD = (CHAIN_SECTION_KEY, "start_slot")
CHAIN_RANGE_SLOT_FIELD = (CHAIN_SECTION_KEY, "range")
CHAIN_IDENTIFIER_FIELD = (CHAIN_SECTION_KEY, "identifier")
CHAIN_INTERVAL_FIELD = (CHAIN_SECTION_KEY, "interval")
CHAIN_EXECUTION_API_FIELD = (CHAIN_SECTION_KEY, "execution_api")
CHAIN_CONSENSUS_API_FIELD = (CHAIN_SECTION_KEY, "consensus_api")
# Keys for strategy section
STRATEGY_SECTION_KEY = "strategy"
STRATEGY_SLOT_PERIOD_FIELD = (STRATEGY_SECTION_KEY, "slot_period")
STRATEGY_MIN_VERIFICATION_DELAY_FIELD = (STRATEGY_SECTION_KEY, "min_verification_delay")
STRATEGY_MAX_VERIFICATION_DELAY_FIELD = (STRATEGY_SECTION_KEY, "max_verification_delay")
STRATEGY_MAX_PENDING_VALIDATORS_FIELD = (STRATEGY_SECTION_KEY, "max_pending_validators")
STRATEGY_PRICE_CHANGE_THRESHOLD_FIELD = (STRATEGY_SECTION_KEY, "price_change_threshold")
STRATEGY_MERKLE_REFRESH_RATE_FIELD = (STRATEGY_SECTION_KEY, "merkle_refresh_rate")
# Keys for network section
NETWORK_SECTION_KEY = "network"
NETWORK_REFRESH_RATE_FIELD = (NETWORK_SECTION_KEY, "refresh_rate")
NETWORK_MAX_ATTEMPT_FEILD = (NETWORK_SECTION_KEY, "max_attempt")
NETWORK_ATTEMPT_RATE_FEILD = (NETWORK_SECTION_KEY, "attempt_rate")
# Keys for logger section
LOGGER_SECTION_KEY = "logger"
LOGGER_DIR_FIELD = (LOGGER_SECTION_KEY, "dir")
LOGGER_LEVEL_FIELD = (LOGGER_SECTION_KEY, "level")
LOGGER_FORMAT_SECTION_KEY = "format"
LOGGER_FORMAT_MESSAGE_FIELD = (LOGGER_SECTION_KEY, LOGGER_FORMAT_SECTION_KEY, "message")
LOGGER_FORMAT_DATE_FIELD = (LOGGER_SECTION_KEY, LOGGER_FORMAT_SECTION_KEY, "date")
LOGGER_BACKUP_SECTION_KEY = "backup"
LOGGER_BACKUP_WHEN_FIELD = (LOGGER_SECTION_KEY, LOGGER_BACKUP_SECTION_KEY, "when")
LOGGER_BACKUP_KEEP_FIELD = (LOGGER_SECTION_KEY, LOGGER_BACKUP_SECTION_KEY, "keep")
# Keys for db section
DB_SECTION_KEY = "db"
DB_DIR_FIELD = (
    DB_SECTION_KEY,
    "dir",
)
DB_BACKUP_SECTION_KEY = "backup"
DB_BACKUP_DIR_FIELD = (DB_SECTION_KEY, DB_BACKUP_SECTION_KEY, "dir")
DB_BACKUP_INTERVAL_FIELD = (DB_SECTION_KEY, DB_BACKUP_SECTION_KEY, "interval")
DB_BACKUP_KEEP_FIELD = (DB_SECTION_KEY, DB_BACKUP_SECTION_KEY, "keep")
# Keys for gas section
GAS_SECTION_KEY = "gas"
GAS_MAX_PRIORITY_FIELD = (GAS_SECTION_KEY, "max_priority")
GAS_MAX_BASE_FIELD = (GAS_SECTION_KEY, "max_base")
GAS_API_FIELD = (GAS_SECTION_KEY, "api")
GAS_PARSER_SECTION_KEY = "parser"
GAS_PARSER_PRIORITY_FIELD = (GAS_SECTION_KEY, GAS_PARSER_SECTION_KEY, "priority")
GAS_PARSER_BASE_FIELD = (GAS_SECTION_KEY, GAS_PARSER_SECTION_KEY, "base")
# Keys for email section
EMAIL_SECTION_KEY = "email"
EMAIL_SENDER_FIELD = (EMAIL_SECTION_KEY, "sender")
EMAIL_RECEIVERS_FIELD = (EMAIL_SECTION_KEY, "receivers")
EMAIL_SMTP_SERVER_FIELD = (EMAIL_SECTION_KEY, "smtp_server")
EMAIL_SMTP_PORT_FIELD = (EMAIL_SECTION_KEY, "smtp_port")
# Keys for watchers field
WATCHERS_FIELD = ("watchers",)


# DEFAULTS
# Chain
DEFAULT_CHAIN_RANGE_SLOT = 3000
DEFAULT_CHAIN_IDENTIFIER = "finalized"
DEFAULT_CHAIN_INTERVAL = 12
# Strategy
DEFAULT_STRATEGY_SLOT_PERIOD = 10
DEFAULT_STRATEGY_MIN_VERIFICATION_DELAY = 3600
DEFAULT_STRATEGY_MAX_VERIFICATION_DELAY = 86400
DEFAULT_STRATEGY_MAX_PENDING_VALIDATORS = 10
DEFAULT_STRATEGY_PRICE_CHANGE_THRESHOLD = 1
DEFAULT_STRATEGY_MERKLE_REFRESH_RATE = 86400
DEFAULT_NETWORK_REFRESH_RATE = 60
DEFAULT_NETWORK_MAX_ATTEMPT = 20
DEFAULT_NETWORK_ATTEMPT_RATE = 0.1
# Logger
DEFAULT_LOGGER_DIR = "logs"
DEFAULT_LOGGER_LEVEL = "INFO"
DEFAULT_LOGGER_FORMAT_MESSAGE = "[%(asctime)s] %(threadName)-29s | %(levelname)-8s :: %(message)s"
DEFAULT_LOGGER_FORMAT_DATE = "%H:%M:%S"
DEFAULT_LOGGER_BACKUP_WHEN = "midnight"
DEFAULT_LOGGER_BACKUP_KEEP = 30
# DB
DEFAULT_DB_DIR = "db"
DEFAULT_DB_BACKUP_DIR = Path.home() / "geoscope"
DEFAULT_DB_BACKUP_INTERVAL = 604800
DEFAULT_DB_BACKUP_KEEP = 1
# Gas
DEFAULT_GAS_PARSER_PRIORITY = "low.suggestedMaxPriorityFeePerGas"
DEFAULT_GAS_PARSER_BASE = "low.suggestedMaxFeePerGas"
# Email
DEFAULT_EMAIL_SMTP_SERVER = "smtp.gmail.com"
DEFAULT_EMAIL_SMTP_PORT = 587


# RANGE LIMITS
MIN_RANGE_VALUE = 1
# Strategy
MAX_STRATEGY_SLOT_PERIOD = 1000
MAX_STRATEGY_MIN_VERIFICATION_DELAY = 3600  # seconds
MAX_STRATEGY_MAX_VERIFICATION_DELAY = 86400  # seconds
MAX_STRATEGY_MAX_PENDING_VALIDATORS = 100
MAX_STRATEGY_PRICE_CHANGE_THRESHOLD = 6
MAX_STRATEGY_MERKLE_REFRESH_RATE = 86400  # seconds
# Network
MAX_NETWORK_REFRESH_RATE = 360  # seconds
MAX_NETWORK_MAX_ATTEMPT = 100
MIN_NETWORK_ATTEMPT_RATE = 0.1  # seconds
MAX_NETWORK_ATTEMPT_RATE = 10  # seconds
# DB
MAX_DB_BACKUP_KEEP = 10
# Gas
MAX_GAS_PRIORITY_FEE = 10000
MAX_GAS_BASE_FEE = 10000
